-- Insert all IPL entries
INSERT INTO ipl_entries (id, module_id, unit_name, ipl_title, goal_text, order_index) VALUES
(1, 1, 'Real Number Systems', 'Ordering Numbers', 'Order numbers using the number line.', 0),
(2, 1, NULL, NULL, 'Order numbers by converting to decimals.', 1),
(3, 1, 'Real Number Systems', 'Scientific Notation 1', 'Compare positive powers of 10.', 2),
(4, 1, NULL, NULL, 'Convert scientific notation to standard form.', 3),
(5, 1, NULL, NULL, 'Write large numbers in scientific notation.', 4),
(6, 1, 'Equations', 'Solving One-Step Equations', 'Solve for an unknown in one-step equations.', 5),
(7, 1, NULL, NULL, NULL, 6),
(8, 1, 'Angles', 'Angles', 'Name the parts of an angle.', 7),
(9, 1, NULL, NULL, 'Name angles using the vertex.', 8),
(10, 1, NULL, NULL, 'Name angles using three points.', 9),
(11, 1, 'Angles', 'Measuring Angles', 'Use a protractor to measure angles.', 10),
(12, 1, NULL, NULL, 'Name angles by their measures.', 11),
(13, 1, 'Ratios and Percents', 'Introduction to Ratios', 'Explore concepts related to ratios.', 12),
(14, 1, NULL, NULL, 'Identify different types of ratios.', 13),
(15, 1, NULL, NULL, 'Determine if two ratios are equivalent.', 14),
(16, 1, 'Accuracy', 'Accuracy and Precision', 'Define accuracy and precision.', 15),
(17, 1, NULL, NULL, 'Distinguish between accuracy and precision.', 16),
(18, 1, NULL, NULL, 'Describe accuracy using the ± symbol.', 17),
(19, 1, 'Polynomials', 'Adding and Subtracting Polynomials', 'Add polynomials.', 18),
(20, 1, NULL, NULL, 'Subtract polynomials.', 19),
(21, 1, NULL, NULL, NULL, 20),
(22, 2, 'Real Number System', 'Real Number System', 'Define set, subset, and superset.', 0),
(23, 2, NULL, NULL, 'Define the real number system and its subsets, which are rational, irrational, integer, whole, and natural.', 1),
(24, 2, NULL, NULL, 'Classify numbers according to their sets.', 2),
(25, 2, 'Integers', 'Integers', 'Define natural numbers, whole numbers, and integers.', 3),
(26, 2, NULL, NULL, 'Identify positive and negative integers and their relationship to zero.', 4),
(27, 2, NULL, NULL, 'Order integers using a number line.', 5),
(28, 2, 'Absolute Value', 'Absolute Value', 'Relate the absolute value of a number with distance from a starting point.', 6),
(29, 2, NULL, NULL, 'Use math to simplify the absolute value of numbers.', 7),
(30, 2, 'Absolute Value', 'Solving Absolute Value Equations', 'Apply the rules of absolute value.', 8),
(31, 2, NULL, NULL, 'Solve absolute value equations.', 9),
(32, 2, 'Angles', 'Angles', 'Name the parts of an angle.', 10),
(33, 2, NULL, NULL, 'Name angles using the vertex.', 11),
(34, 2, NULL, NULL, 'Name angles using three points.', 12),
(35, 2, 'Angles', 'Measuring Angles', 'Use a protractor to measure angles.', 13),
(36, 2, NULL, NULL, 'Name angles by their measures.', 14),
(37, 2, 'Angle Relationships', 'Angle Relationships', 'Define and identify congruent angles.', 15),
(38, 2, NULL, NULL, 'Define and identify an angle bisector.', 16),
(39, 2, NULL, NULL, 'Define and identify complementary and supplementary angles.', 17),
(40, 2, 'Data Graphs I', 'Central Tendency', 'Calculate mean, median, mode, and range.', 18),
(41, 3, 'Real Number System', 'Scientific Notation I', 'Compare positive powers of 10.', 0),
(42, 3, NULL, NULL, 'Convert scientific notation to standard form.', 1),
(43, 3, NULL, NULL, 'Write large numbers in scientific notation.', 2),
(44, 3, 'Real Number System', 'Scientific Notation II', 'Compare negative powers of 10.', 3),
(45, 3, NULL, NULL, 'Convert scientific notation to standard form.', 4),
(46, 3, NULL, NULL, 'Convert standard form to scientific notation.', 5),
(47, 3, 'Equations', 'Combining Like Terms', 'Identify different parts of a term.', 6),
(48, 3, NULL, NULL, 'Locate like terms.', 7),
(49, 3, NULL, NULL, 'Combine like terms using addition and subtraction.', 8),
(50, 3, 'Exponents', 'Exponents', 'Write repeated multiplications in exponential form.', 9),
(51, 3, NULL, NULL, 'Find the value of exponential expressions.', 10),
(52, 3, 'Exponents', 'Properties of Exponents I', 'Explore the Product of Powers Property.', 11),
(53, 3, NULL, NULL, 'Explore the Power of a Power Property.', 12),
(54, 3, NULL, NULL, 'Explore the Power of a Product Property.', 13),
(55, 3, 'Exponents', 'Properties of Exponents II', 'Explore zero exponents.', 14),
(56, 3, NULL, NULL, 'Explore negative exponents.', 15),
(57, 3, NULL, NULL, 'Explore and apply the Quotient of Powers Property.', 16),
(58, 3, NULL, NULL, 'Explore and apply the Power of a Quotient Property.', 17),
(59, 3, 'Inequalities', 'Inequalities', 'Set up inequalities from verbal sentences.', 18),
(60, 3, NULL, NULL, 'Graph inequalities on a number line.', 19),
(61, 3, 'Inequalities', 'Solving Inequalities', 'Solve simple inequalities using algebra properties.', 20),
(62, 4, 'Polynomials', 'Monomials', 'Identify monomial expressions.', 0),
(63, 4, NULL, NULL, 'Multiply monomials.', 1),
(64, 4, NULL, NULL, 'Divide monomials.', 2),
(65, 4, 'Polynomials', 'Polynomials', 'Identify different types of polynomials.', 3),
(66, 4, NULL, NULL, 'Find the degree of polynomials.', 4),
(67, 4, NULL, NULL, 'Order polynomials.', 5),
(68, 4, 'Polynomials', 'Adding and Subtracting Polynomials', 'Add polynomials.', 6),
(69, 4, NULL, NULL, 'Subtract polynomials.', 7),
(70, 4, 'Polynomials', 'Multiplying Polynomials', 'Multiply polynomials with the Distributive Property.', 8),
(71, 4, NULL, NULL, 'Multiply polynomials using the FOIL method.', 9),
(72, 4, 'Polynomials', 'Special Products of Polynomials', 'Find the square of a sum.', 10),
(73, 4, NULL, NULL, 'Find a square of a difference.', 11),
(74, 4, NULL, NULL, 'Find the product of a sum and a difference.', 12),
(75, 4, 'Ratios and Percents', 'Percent Change', 'Calculate percent change.', 13),
(76, 4, NULL, NULL, 'Determine if percent change is an increase or a decrease.', 14),
(77, 4, 'Matrices', 'Matrices – Data Collection', 'Learn how to use matrix notation.', 15),
(78, 4, NULL, NULL, 'Use matrices to store and interpret data.', 16),
(79, 4, 'Matrices', 'Matrices – Addition and Subtraction', 'Add matrices.', 17),
(80, 4, NULL, NULL, 'Subtract matrices.', 18),
(81, 4, NULL, NULL, 'Learn about matrices of equal size.', 19),
(82, 5, 'Equations', 'Solving One-Step Equations', 'Solve for an unknow in one-step equations.', 0),
(83, 5, 'Ratios and Percents', 'Percents', 'Define percent.', 1),
(84, 5, NULL, NULL, 'Represent percents graphically.', 2),
(85, 5, NULL, NULL, 'Convert percents to decimals and decimals to percents.', 3),
(86, 5, NULL, NULL, 'Convert fractions to percents and percents to fractions.', 4),
(87, 5, 'Ratios and Percents', 'Percent Change', 'Calculate percent change.', 5),
(88, 5, NULL, NULL, 'Determine if percent change is an increase or a decrease.', 6),
(89, 5, 'Ratios and Percents', 'Introduction to Ratios', 'Explore concepts related to ratios.', 7),
(90, 5, NULL, NULL, 'Identify different types of ratios.', 8),
(91, 5, NULL, NULL, 'Determine if two ratios are equivalent.', 9),
(92, 5, 'Ratios and Percents', 'Proportions and Unknowns', 'Explore the concepts of proportions.', 10),
(93, 5, NULL, NULL, 'Identify the different parts of a proportion.', 11),
(94, 5, NULL, NULL, 'Apply knowledge of proportions to solve for unknowns.', 12),
(95, 5, 'Functions', 'Functions', 'Identify a function and its notation.', 13),
(96, 5, NULL, NULL, 'Determine the domain and range of a function.', 14),
(97, 5, NULL, NULL, 'Determine whether a relation is a function.', 15),
(98, 5, 'Linear Equations & Graphing', 'Linear and Nonlinear', 'Determine if a graph is linear or nonlinear.', 16),
(99, 5, NULL, NULL, 'Determine if an equation will generate a linear or nonlinear graph.', 17),
(100, 6, 'Triangles', 'Introduction to Triangles', 'Define and label the parts of a triangle.', 0),
(101, 6, NULL, NULL, 'Name triangles.', 1),
(102, 6, NULL, NULL, 'Calculate missing angle measures.', 2),
(103, 6, 'Triangles', 'Congruent Triangles', 'Prove congruency with the Side-Side-Side Theorem.', 3),
(104, 6, NULL, NULL, 'Prove congruency with the Side-Angle-Side Theorem.', 4),
(105, 6, NULL, NULL, 'Prove congruency with the Angle-Side-Angle Theorem.', 5),
(106, 6, 'Triangles', 'Similar Triangles', 'Write proportions for similar triangles.', 6),
(107, 6, NULL, NULL, 'Prove two triangles similar using SSS and SAS Similarity.', 7),
(108, 6, NULL, NULL, 'Prove two triangles similar using AA Similarity.', 8),
(109, 6, 'Triangles', 'Inequality, Right Triangles, and the Pythagorean Theorem', 'Use the Triangle Inequality Theorem to determine whether you can draw a triangle.', 9),
(110, 6, NULL, NULL, 'Identify the parts of a right triangle.', 10),
(111, 6, NULL, NULL, 'Solve for the missing side of a right triangle using the Pythagorean Theorem.', 11),
(112, 6, 'Angles', 'Introduction to Geometry', 'Define and name points.', 12),
(113, 6, NULL, NULL, 'Define and name lines, rays, and segments.', 13),
(114, 6, NULL, NULL, 'Define and name planes.', 14),
(115, 6, 'Angles', 'Parallel, Perpendicular, and Skew Lines', 'Define and label parallel lines.', 15),
(116, 6, NULL, NULL, 'Define and label perpendicular lines.', 16),
(117, 6, NULL, NULL, 'Define and label skew lines.', 17),
(118, 6, 'Linear Equations & Graphing', 'Distant and Midpoint Formulas', 'Calculate the distance between two points using the Distance Formula.', 18),
(119, 6, NULL, NULL, 'Determine the midpoint between two points using the Midpoint Formula.', 19),
(120, 6, 'Linear Equations & Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 20),
(121, 6, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 21),
(122, 6, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 22),
(123, 7, 'Polynomials', 'Adducing and Subtracting Polynomials', 'Add polynomials.', 0),
(124, 7, NULL, NULL, 'Subtract polynomials.', 1),
(125, 7, 'Polynomials', 'Multiplying Polynomials', 'Multiply polynomials with the Distributive Property.', 2),
(126, 7, NULL, NULL, 'Multiply polynomials using the FOIL method.', 3),
(127, 7, 'Factoring', 'Factoring Algebraic Terms', 'Factor to find the GCF.', 4),
(128, 7, NULL, NULL, 'Factor algebraic terms.', 5),
(129, 7, 'Factoring', 'Factoring with the Distributive Property', 'Factor simple algebraic expressions using the Distributive Property.', 6),
(130, 7, 'Factoring', 'Factoring with FOIL I', 'Factor quadratics in the form x2 + bx + c using FOIL', 7),
(131, 7, NULL, NULL, 'Solve factored quadratics.', 8),
(132, 7, 'Factoring', 'Factoring with FOIL II', 'Factor quadratics in the form ax2 + bx + c using FOIL.', 9),
(133, 7, NULL, NULL, 'Solve factored quadratics.', 10),
(134, 7, 'Factoring', 'Factoring Perfect Square Trinomials', 'Identify perfect square trinomials.', 11),
(135, 7, NULL, NULL, 'Factor perfect square trinomials.', 12),
(136, 7, NULL, NULL, 'Apply the Perfect Square Property.', 13),
(137, 7, 'Factoring', 'Completing the Square', 'Solve quadratic equations by completing the square.', 14),
(138, 8, 'Functions', 'Functions', 'Identify a function and its notation.', 0),
(139, 8, NULL, NULL, 'Determine the domain and range of a function.', 1),
(140, 8, NULL, NULL, 'Determine whether a relation is a function.', 2),
(141, 8, 'Equations', 'Solving One-Step Equations', 'Solve for an unknow in one-step equations.', 3),
(142, 8, 'Equations', 'Multistep Equations', 'Solve multistep equations.', 4),
(143, 8, 'Properties of Real Numbers', 'Substitution', 'Use substitution to solve one-variable equations.', 5),
(144, 8, NULL, NULL, 'Use substitution to solve two-variable equations.', 6),
(145, 8, NULL, NULL, 'Substitute expressions in variables.', 7),
(146, 8, 'Radicals', 'Perfect Squares and Square Roots', 'Identify perfect squares.', 8),
(147, 8, NULL, NULL, 'Find the square root of perfect squares.', 9),
(148, 8, NULL, NULL, 'Approximate the square root of whole numbers.', 10),
(149, 8, 'Linear Equations & Graphing', 'The Coordinate Plane', 'Define an identify parts of the coordinate plane.', 11),
(150, 8, NULL, NULL, 'Identify the quadrants of the coordinate plane.', 12),
(151, 8, NULL, NULL, 'Plot ordered pairs.', 13),
(152, 8, 'Linear Equations & Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 14),
(153, 8, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 15),
(154, 8, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 16),
(155, 8, 'Linear Equations & Graphing', 'Slope-Intercept Form', 'Write an equation in slope-intercept form.', 17),
(156, 8, NULL, NULL, 'Graph an equation in slope-intercept form.', 18),
(157, 8, NULL, NULL, 'Find an equation from a graph.', 19),
(158, 9, 'Prisms and Pyramids', 'Cubes', 'Identify a cube and its parts.', 0),
(159, 9, NULL, NULL, 'Calculate the surface area of a cube.', 1),
(160, 9, NULL, NULL, 'Calculate the volume of a cube.', 2),
(161, 9, 'Prisms and Pyramids', 'Rectangular Prisms', 'Identify rectangular prisms and their properties.', 3),
(162, 9, NULL, NULL, 'Find the surface area of a rectangular prism.', 4),
(163, 9, NULL, NULL, 'Find the volume of a rectangular prism.', 5),
(164, 9, 'Prisms and Pyramids', 'Rectangular Pyramids', 'Identify the height of a rectangular pyramid.', 6),
(165, 9, NULL, NULL, 'Find the surface area of a rectangular pyramid.', 7),
(166, 9, NULL, NULL, 'Find the volume of a rectangular pyramid.', 8),
(167, 9, 'Circles', 'Spheres', 'Identify spheres and their parts.', 9),
(168, 9, NULL, NULL, 'Find the surface area of a sphere.', 10),
(169, 9, NULL, NULL, 'Find the volume of a sphere.', 11),
(170, 9, 'Transformations', 'Translations', 'Apply translation to plotted points.', 12),
(171, 9, NULL, NULL, 'Apply translation to plotted lines.', 13),
(172, 9, NULL, NULL, 'Apply translation to plotted shapes.', 14),
(173, 9, 'Transformations', 'Reflections', 'Understand the line of reflection.', 15),
(174, 9, NULL, NULL, 'Reflect points across the x- and y-axes.', 16),
(175, 9, NULL, NULL, 'Reflect shapes across the x- and y-axes.', 17),
(176, 9, NULL, NULL, 'Reflect shapes across a given line.', 18),
(177, 9, 'Transformations', 'Rotations', 'Determine an object’s rotational symmetry.', 19),
(178, 9, NULL, NULL, 'Identify the angle of rotation.', 20),
(179, 9, NULL, NULL, 'Rotate shapes on the coordinate plane.', 21),
(180, 9, 'Transformations', 'Dilations', 'Plot points for dilated shapes.', 22),
(181, 9, NULL, NULL, 'Identify the scale factor of a shape.', 23),
(182, 9, NULL, NULL, 'Plot shapes around the center of dilation.', 24),
(183, 10, 'Data Graphs II', 'Scatter Plots', 'Create scatter plots.', 0),
(184, 10, NULL, NULL, 'Analyze scatter plots to determine relationships.', 1),
(185, 10, 'Linear Equations & Graphing', 'The Coordinate Plane', 'Define an identify parts of the coordinate plane.', 2),
(186, 10, NULL, NULL, 'Identify the quadrants of the coordinate plane.', 3),
(187, 10, NULL, NULL, 'Plot ordered pairs.', 4),
(188, 10, 'Linear Equations & Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 5),
(189, 10, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 6),
(190, 10, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 7),
(191, 10, 'Linear Equations & Graphing', 'Slope-Intercept Form', 'Write an equation in slope-intercept form.', 8),
(192, 10, NULL, NULL, 'Graph an equation in slope-intercept form.', 9),
(193, 10, NULL, NULL, 'Find an equation from a graph.', 10),
(194, 10, 'Linear Equations & Graphing', 'Standard Form', 'Write an equation in standard form.', 11),
(195, 10, NULL, NULL, 'Graph an equation in standard form.', 12),
(196, 10, 'Linear Equations & Graphing', 'Point-Slope Form', 'Write an equation in point-slope form.', 13),
(197, 10, NULL, NULL, 'Graph an equation in point-slope form.', 14),
(198, 10, NULL, NULL, 'Find an equation from a graph.', 15),
(199, 10, 'Equations', 'Variables and Variation', 'Identify and solve direct variation equations.', 16),
(200, 10, NULL, NULL, 'Identify and solve inverse variation equations.', 17),
(201, 10, 'Transformations', 'Points, Lines, and Shapes', 'Plot ordered pairs.', 18),
(202, 10, NULL, NULL, 'Connect plotted points.', 19),
(203, 10, NULL, NULL, 'Create shapes from plotted points.', 20),
(204, 11, 'Polygons', 'Quadrilaterals, Rectangles, and Squares', 'Learn and identify the properties of quadrilaterals.', 0),
(205, 11, NULL, NULL, 'Identify rectangles and their properties.', 1),
(206, 11, NULL, NULL, 'Identify squares and their properties.', 2),
(207, 11, 'Polygons', 'Trapezoids and Kites', 'Identify a trapezoid and its properties.', 3),
(208, 11, NULL, NULL, 'Identify a kite and its properties.', 4),
(209, 11, 'Polygons', 'Area', 'Find the area of a rectangle.', 5),
(210, 11, NULL, NULL, 'Find the area of a triangle.', 6),
(211, 11, NULL, NULL, 'Find the area of a trapezoid.', 7),
(212, 11, 'Polygons', 'Area of Irregular Shapes', 'Break irregular shapes into polygons.', 8),
(213, 11, NULL, NULL, 'Calculate the area of irregular shapes.', 9),
(214, 11, NULL, NULL, 'Find the area of shaded portions of circles.', 10),
(215, 11, 'Triangles', 'Inequality, Right Triangles, and the Pythagorean', 'Use the Triangle Inequality Theorem to determine whether you can draw a triangle.', 11),
(216, 11, NULL, 'Theorem', 'Identify the parts of a right triangle.', 12),
(217, 11, NULL, NULL, 'Solve for the missing side of a right triangle using the Pythagorean Theorem.', 13),
(218, 11, 'Units', 'Standard Units', 'Recognize the standard base units.', 14),
(219, 11, NULL, NULL, 'Identify the property each standard base unit measures.', 15),
(220, 11, NULL, NULL, 'Choose the correct unit to measure an object.', 16),
(221, 11, 'Circles', 'Circumference and Area', 'Evaluate expressions with pi.', 17),
(222, 11, NULL, NULL, 'Find the circumference of a circle.', 18),
(223, 11, NULL, NULL, 'Find the area of a circle.', 19),
(224, 11, 'Circles', 'Cylinders', 'Define a cylinder and its parts.', 20),
(225, 11, NULL, NULL, 'Find the surface area of a cylinder.', 21),
(226, 11, NULL, NULL, 'Find the volume of a cylinder.', 22),
(227, 12, 'Equations', 'Combining Like Terms', 'Identify different parts of a term.', 0),
(228, 12, NULL, NULL, 'Locate like terms.', 1),
(229, 12, NULL, NULL, 'Combine like terms using addition and subtraction.', 2),
(230, 12, 'Equations', 'Solving One-Step Equations', 'Solve for an unknow in one-step equations.', 3),
(231, 12, 'Equations', 'Multistep Equations', 'Solve multistep equations.', 4),
(232, 12, 'Equations', 'Rate Equations', 'Solve problems using the percentage formula.', 5),
(233, 12, NULL, NULL, 'Solve problems using the distance formula.', 6),
(234, 12, 'Ratios and Percents', 'Percents', 'Define percent.', 7),
(235, 12, NULL, NULL, 'Represent percents graphically.', 8),
(236, 12, NULL, NULL, 'Convert percents to decimals and decimals to percents.', 9),
(237, 12, NULL, NULL, 'Convert fractions to percents and percents to fractions.', 10),
(238, 12, 'Ratios and Percents', 'Percent Change', 'Calculate percent change.', 11),
(239, 12, NULL, NULL, 'Determine if percent change is an increase or a decrease.', 12),
(240, 12, 'Ratios and Percents', 'Introduction to Ratios', 'Explore concepts related to ratios.', 13),
(241, 12, NULL, NULL, 'Identify different types of ratios.', 14),
(242, 12, NULL, NULL, 'Determine if two ratios are equivalent.', 15),
(243, 12, 'Ratios and Percents', 'Proportions and Unknowns', 'Explore the concepts of proportions.', 16),
(244, 12, NULL, NULL, 'Identify the different parts of a proportion.', 17),
(245, 12, NULL, NULL, 'Apply knowledge of proportions to solve for unknowns.', 18),
(246, 13, 'Angle Relationships', 'Angle Relationships', 'Define and identify congruent angles.', 0),
(247, 13, NULL, NULL, 'Define and identify an angle bisector.', 1),
(248, 13, NULL, NULL, 'Define and identify complementary and supplementary angles.', 2),
(249, 13, 'Angle Relationships', 'The Transversal', 'Define and identify a transversal.', 3),
(250, 13, NULL, NULL, 'Define and identify corresponding angles.', 4),
(251, 13, 'Triangles', 'Classifying Triangles', 'Identify and classify triangles by their angle measures.', 5),
(252, 13, NULL, NULL, 'Identify and classify triangles by their side lengths.', 6),
(253, 13, 'Angles', 'Parallel, Perpendicular, and Skew Lines', 'Define and label parallel lines.', 7),
(254, 13, NULL, NULL, 'Define and label perpendicular lines.', 8),
(255, 13, NULL, NULL, 'Define and label skew lines.', 9),
(256, 13, 'Absolute Value', 'Absolute Value', 'Relate the absolute value of a number with distance from a starting point.', 10),
(257, 13, NULL, NULL, 'Use math to simplify the absolute value of numbers.', 11),
(258, 13, 'Absolute Value', 'Solving Absolute Value Equations', 'Apply the rules of absolute value.', 12),
(259, 13, NULL, NULL, 'Solve absolute value equations.', 13),
(260, 13, 'Linear Equations & Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 14),
(261, 13, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 15),
(262, 13, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 16),
(263, 13, 'Linear Equations & Graphing', 'Slope-Intercept Form', 'Write an equation in slope-intercept form.', 17),
(264, 13, NULL, NULL, 'Graph an equation in slope-intercept form.', 18),
(265, 13, NULL, NULL, 'Find an equation from a graph.', 19),
(266, 14, 'Equations', 'Rate Equations', 'Solve problems using the percentage formula.', 0),
(267, 14, NULL, NULL, 'Solve problems using the distance formula.', 1),
(268, 14, 'Equations', 'Simplifying to Solve Equations', 'Simplify to solve equations.', 2),
(269, 14, 'Equations', 'Variables and Variation', 'Identify and solve direct variation equations.', 3),
(270, 14, NULL, NULL, 'Identify and solve inverse variation equations.', 4),
(271, 14, 'Special Equations', 'Complex Fractions', 'Define mixed expressions and complex fractions.', 5),
(272, 14, NULL, NULL, 'Simplify mixed expressions and complex fractions.', 6),
(273, 14, 'Special Equations', 'Rational Equations', 'Solve for x in rational equations.', 7),
(274, 14, 'Exponents', 'Exponents', 'Write repeated multiplications in exponential form.', 8),
(275, 14, NULL, NULL, 'Find the value of exponential expressions.', 9),
(276, 14, 'Exponents', 'Properties of Exponents I', 'Explore the Product of Powers Property.', 10),
(277, 14, NULL, NULL, 'Explore the Power of a Power Property.', 11),
(278, 14, NULL, NULL, 'Explore the Power of a Product Property.', 12),
(279, 14, 'Exponents', 'Properties of Exponents II', 'Explore zero exponents.', 13),
(280, 14, NULL, NULL, 'Explore negative exponents.', 14),
(281, 14, NULL, NULL, 'Explore and apply the Quotient of Powers Property.', 15),
(282, 14, NULL, NULL, 'Explore and apply the Power of a Quotient Property.', 16),
(283, 15, 'Real Number System', 'Order of Operations', 'Apply the order of operations to solve simple and complex expressions.', 0),
(284, 15, 'Ratios and Percents', 'Percents', 'Define percent.', 1),
(285, 15, NULL, NULL, 'Represent percents graphically.', 2),
(286, 15, NULL, NULL, 'Convert percents to decimals and decimals to percents.', 3),
(287, 15, NULL, NULL, 'Convert fractions to percents and percents to fractions.', 4),
(288, 15, 'Ratios and Percents', 'Percent Change', 'Calculate percent change.', 5),
(289, 15, NULL, NULL, 'Determine if percent change is an increase or a decrease.', 6),
(290, 15, 'Ratios and Percents', 'Introduction to Ratios', 'Explore concepts related to ratios.', 7),
(291, 15, NULL, NULL, 'Identify different types of ratios.', 8),
(292, 15, NULL, NULL, 'Determine if two ratios are equivalent.', 9),
(293, 15, 'Ratios and Percents', 'Proportions and Unknowns', 'Explore the concepts of proportions.', 10),
(294, 15, NULL, NULL, 'Identify the different parts of a proportion.', 11),
(295, 15, NULL, NULL, 'Apply knowledge of proportions to solve for unknowns.', 12),
(296, 15, 'Properties of Real Numbers', 'Substitution', 'Use substitution to solve one-variable equations.', 13),
(297, 15, NULL, NULL, 'Use substitution to solve two-variable equations.', 14),
(298, 15, NULL, NULL, 'Substitute expressions in variables.', 15),
(299, 15, 'Equations', 'One-Step Equation Word Problems', 'Solve one-step equations from word problems.', 16),
(300, 15, NULL, NULL, 'Solve one-step equations with decimals and fractions.', 17),
(301, 15, 'Equations', 'Multistep Equations', 'Solve multistep equations.', 18),
(302, 16, 'Inequalities', 'Inequalities', 'Set up inequalities from verbal sentences.', 0),
(303, 16, NULL, NULL, 'Graph inequalities on a number line.', 1),
(304, 16, 'Inequalities', 'Solving Inequalities', 'Solve simple inequalities using algebra properties.', 2),
(305, 16, 'Inequalities', 'Solving Compound Inequalities', 'Write a compound inequality.', 3),
(306, 16, NULL, NULL, 'Solve a compound inequality.', 4),
(307, 16, 'Linear Equations & Graphing', 'Linear and Nonlinear', 'Determine if a graph is linear or nonlinear.', 5),
(308, 16, NULL, NULL, 'Determine if an equation will generate a linear or nonlinear graph.', 6),
(309, 16, 'Radicals', 'Simplifying Square Roots', 'Find the principal and negative square root.', 7),
(310, 16, NULL, NULL, 'Simplify square roots to find the exact answer.', 8),
(311, 16, 'Radicals', 'Radical Expressions', 'Simplify radical expressions.', 9),
(312, 16, 'Radicals', 'Radical Expressions-Operations', 'Identify and solve direct variation equations.', 10),
(313, 16, NULL, NULL, 'Identify and solve inverse variation equations.', 11),
(314, 16, 'Special Equations', 'Radical Equations', 'Solve for x in rational equations.', 12),
(315, 17, 'Functions', 'Functions', 'Identify a function and its notation.', 0),
(316, 17, NULL, NULL, 'Determine the domain and range of a function.', 1),
(317, 17, NULL, NULL, 'Determine whether a relation is a function.', 2),
(318, 17, 'Functions', 'Graphing Functions', 'Identify the graphs of linear, quadratic, and absolute value functions.', 3),
(319, 17, NULL, NULL, 'Identify the graph of a step function.', 4),
(320, 17, NULL, NULL, 'Use the vertical line test to determine if a graph is a function.', 5),
(321, 17, 'Exponential Equations', 'Exponential Functions', 'Find ordered pairs of exponential functions.', 6),
(322, 17, NULL, NULL, 'Find the y-intercept of an exponential function.', 7),
(323, 17, NULL, NULL, 'Identify the graph of an exponential function.', 8),
(324, 17, 'Exponential Equations', 'Exponential Growth', 'Review conversion of a percent to a decimal.', 9),
(325, 17, NULL, NULL, 'Identify and use the formula for exponential growth.', 10),
(326, 17, NULL, NULL, 'Calculate exponential growth and compound interest.', 11),
(327, 17, 'Exponential Equations', 'Exponential Decay', 'Identify and use the formula for exponential decay.', 12),
(328, 17, NULL, NULL, 'Solve depreciation problems.', 13),
(329, 17, NULL, NULL, 'Identify and use the half-life formula.', 14),
(330, 17, 'Quadratics', 'Graphing Quadratics I', 'Identify quadratics.', 15),
(331, 17, NULL, NULL, 'Find the maximum or minimum on a graph.', 16),
(332, 17, NULL, NULL, 'Graph quadratics.', 17),
(333, 18, 'Factoring', 'Factoring with FOIL I', 'Factor quadratics in the form x2 + bx + c using FOIL', 0),
(334, 18, NULL, NULL, 'Solve factored quadratics.', 1),
(335, 18, 'Factoring', 'Factoring with FOIL II', 'Factor quadratics in the form ax2 + bx + c using FOIL.', 2),
(336, 18, NULL, NULL, 'Solve factored quadratics.', 3),
(337, 18, 'Factoring', 'Factoring Perfect Square Trinomials', 'Identify perfect square trinomials.', 4),
(338, 18, NULL, NULL, 'Factor perfect square trinomials.', 5),
(339, 18, NULL, NULL, 'Apply the Perfect Square Property.', 6),
(340, 18, 'Quadratics', 'Graphing Quadratics I', 'Identify quadratics.', 7),
(341, 18, NULL, NULL, 'Find the maximum or minimum on a graph.', 8),
(342, 18, NULL, NULL, 'Graph quadratics.', 9),
(343, 18, 'Quadratics', 'Graphing Quadratics II', 'Find the axis of symmetry of a parabola.', 10),
(344, 18, NULL, NULL, 'Graph a quadratic using the axis of symmetry.', 11),
(345, 18, NULL, NULL, 'Adjust the width of a parabola.', 12),
(346, 18, NULL, NULL, 'Shift a parabola by changing the constant.', 13),
(347, 18, 'Quadratics', 'Solving Quadratics by Graphing', 'Solve a quadratic by graphing.', 14),
(348, 18, NULL, NULL, 'Identify the types of solutions a quadratic can have.', 15),
(349, 18, 'Quadratics', 'Quadratic Formula', 'Solve quadratics using the Quadratic Formula.', 16),
(350, 18, 'Quadratics', 'The Discriminant', 'Use the discriminant to find the number of real roots in a quadratic.', 17),
(351, 18, NULL, NULL, 'Find the discriminant to verify the roots of a quadratic.', 18),
(352, 19, 'Real Number System', 'Real Number System', 'Define set, subset, and superset.', 0),
(353, 19, NULL, NULL, 'Define the real number system and its subsets, which are rational, irrational, integer, whole, and natural.', 1),
(354, 19, NULL, NULL, 'Classify numbers according to their sets.', 2),
(355, 19, 'Real Number System', 'Ordering Numbers', 'Order numbers using the number line.', 3),
(356, 19, NULL, NULL, 'Order numbers by converting to decimals.', 4),
(357, 19, 'Real Number System', 'Order of Operations', 'Apply the order of operations to solve simple and complex expressions.', 5),
(358, 19, 'Real Number System', 'Prime Factorization', 'Learn about prime and composite numbers.', 6),
(359, 19, NULL, NULL, 'Find factors of natural numbers.', 7),
(360, 19, NULL, NULL, 'Find prime factorizations of natural numbers.', 8),
(361, 19, 'Properties of Real Numbers', 'Properties of Equality I', 'Apply to Reflexive Property of Equality of real numbers.', 9),
(362, 19, NULL, NULL, 'Use the Symmetric Property of Equality of real numbers.', 10),
(363, 19, NULL, NULL, 'Explore the Transitive Property of Equality of real numbers.', 11),
(364, 19, 'Properties of Real Numbers', 'Properties of Equality II', 'Apply the Addition Property of Equality', 12),
(365, 19, NULL, NULL, 'Apply the Subtraction Property of Equality', 13),
(366, 19, NULL, NULL, 'Apply the Multiplication Property of Equality', 14),
(367, 19, NULL, NULL, 'Apply the Division Property of Equality', 15),
(368, 19, 'Properties of Real Numbers', 'Commutative Properties', 'Explore the Commutative Property of Addition', 16),
(369, 19, NULL, NULL, 'Apply the Commutative Property of Multiplication', 17),
(370, 19, 'Properties of Real Numbers', 'Associative Properties', 'Explore the Associative Properties of Addition and Multiplication to evaluate expressions.', 18),
(371, 19, NULL, NULL, 'Use the Associative Properties of Addition and Multiplication to solve expressions.', 19),
(372, 20, 'Data Graphs I', 'Bar Graphs and Histograms', 'Analyze data in bar graphs, double-bar graphs, and histograms.', 0),
(373, 20, NULL, NULL, 'Learn the steps to create a histogram.', 1),
(374, 20, 'Data Graphs I', 'Box and Whisker Plots', 'Understand quartiles.', 2),
(375, 20, NULL, NULL, 'Identify the parts of box-and-whisker plot.', 3),
(376, 20, NULL, NULL, 'Learn how to show data in box-and-whisker plots.', 4),
(377, 20, 'Matrices', 'Matrices – Data Collection', 'Learn how to use matrix notation.', 5),
(378, 20, NULL, NULL, 'Use matrices to store and interpret data.', 6),
(379, 20, 'Matrices', 'Matrices – Addition and Subtraction', 'Add matrices.', 7),
(380, 20, NULL, NULL, 'Subtract matrices.', 8),
(381, 20, NULL, NULL, 'Learn about matrices of equal size.', 9),
(382, 20, 'Matrices', 'Matrices – Multiplication', 'Learn how to multiply matrices by a scaler.', 10),
(383, 20, NULL, NULL, 'Learn how to multiply matrices together.', 11),
(384, 20, 'Probability', 'Fundamental Counting Principle', 'Calculate the number of possible events using the Fundamental Counting Principle.', 12),
(385, 20, NULL, NULL, 'Determine if events are independent of dependent.', 13),
(386, 20, 'Probability', 'Permutations', 'Learn about factorials.', 14),
(387, 20, NULL, NULL, 'Solve repeating permutations.', 15),
(388, 20, NULL, NULL, 'Solve non-repeating permutations.', 16),
(389, 20, 'Probability', 'Combinations', 'Learn the difference between permutations and combinations.', 17),
(390, 20, NULL, NULL, 'Solve repeating combinations.', 18),
(391, 20, NULL, NULL, 'Solve non-repeating combinations.', 19),
(392, 21, 'Data Graphs I', 'Bar Graphs and Histograms', 'Analyze data in bar graphs, double-bar graphs, and histograms.', 0),
(393, 21, NULL, NULL, 'Learn the steps to create a histogram.', 1),
(394, 21, 'Data Graphs I', 'Organizing Data', 'Evaluate data to crate stem-and-leaf plots.', 2),
(395, 21, NULL, NULL, 'Use back-to-back stem-and-leaf plots.', 3),
(396, 21, NULL, NULL, 'Create a line plot.', 4),
(397, 21, 'Data Graphs I', 'Box and Whisker Plots', 'Understand quartiles.', 5),
(398, 21, NULL, NULL, 'Identify the parts of box-and-whisker plot.', 6),
(399, 21, NULL, NULL, 'Learn how to show data in box-and-whisker plots.', 7),
(400, 21, 'Data Graphs II', 'Population and Sampling', 'Determine a population, sample, and sample size.', 8),
(401, 21, NULL, NULL, 'Learn about sampling techniques.', 9),
(402, 21, 'Probability', 'Fundamental Counting Principle', 'Calculate the number of possible events using the Fundamental Counting Principle.', 10),
(403, 21, NULL, NULL, 'Determine if events are independent of dependent.', 11),
(404, 21, 'Probability', 'Probability', 'Learn about probability and how likely an event is to occur.', 12),
(405, 21, NULL, NULL, 'Discover theoretical probability.', 13),
(406, 21, NULL, NULL, 'Discover experimental probability.', 14),
(407, 21, 'Probability', 'Probability of Independent and Dependent Events', 'Decide if events are independent or dependent.', 15),
(408, 21, NULL, NULL, 'Solve independent events.', 16),
(409, 21, NULL, NULL, 'Solve dependent events.', 17),
(410, 21, 'Probability', 'Probability and Compound Events', 'Decide if events are exclusive or inclusive.', 18),
(411, 21, NULL, NULL, 'Solve exclusive compound events.', 19),
(412, 21, NULL, NULL, 'Solve inclusive compound events.', 20),
(413, 22, 'Equations', 'Multistep Equations', 'Solve multistep equations.', 0),
(414, 22, 'Equations', 'Simplifying to Solve Equations', 'Simplify to solve equations.', 1),
(415, 22, 'Linear Equations and Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 2),
(416, 22, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 3),
(417, 22, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 4),
(418, 22, 'Systems of Equations', 'Systems of Equations - Graphs', 'Define system of linear equations.', 5),
(419, 22, NULL, NULL, 'Find solutions to systems of linear equations by using graphs.', 6),
(420, 22, NULL, NULL, 'Determine the number of solutions to a system of linear equations.', 7),
(421, 22, 'Systems of Equations', 'Systems of Linear Equations - Substitution', 'Isolate a variable in an equation.', 8),
(422, 22, NULL, NULL, 'Solve systems of linear equations using substitution.', 9),
(423, 22, 'Systems of Equations', 'System of Equations – Eliminations', 'Use elimination to solve systems of equations.', 10),
(424, 22, NULL, NULL, 'Use systems of equations to solve story problems.', 11),
(425, 22, 'Graphing Calculators', 'Graphing Calculators I', 'Use a graphing calculator to graph equations.', 12),
(426, 22, NULL, NULL, 'Reset the window settings to see the graph.', 13),
(427, 22, NULL, NULL, 'Use the ZOOM key to zoom in and out on the graph.', 14),
(428, 22, 'Graphing Calculators', 'Graphing Calculators II', 'Graph equations and find corresponding y-values for any x-value.', 15),
(429, 22, NULL, NULL, 'Use calculator functions to find roots and vertices of parabolas.', 16),
(430, 23, 'Equations', 'Solving One-Step Equations', 'Solve for an unknow in one-step equations.', 0),
(431, 23, 'Exponents', 'Exponents', 'Write repeated multiplications in exponential form.', 1),
(432, 23, NULL, NULL, 'Find the value of exponential expressions.', 2),
(433, 23, 'Exponents', 'Properties of Exponents I', 'Explore the Product of Powers Property.', 3),
(434, 23, NULL, NULL, 'Explore the Power of a Power Property.', 4),
(435, 23, NULL, NULL, 'Explore the Power of a Product Property.', 5),
(436, 23, 'Exponents', 'Properties of Exponents II', 'Explore zero exponents.', 6),
(437, 23, NULL, NULL, 'Explore negative exponents.', 7),
(438, 23, NULL, NULL, 'Explore and apply the Quotient of Powers Property.', 8),
(439, 23, NULL, NULL, 'Explore and apply the Power of a Quotient Property.', 9),
(440, 23, 'Real Number System', 'Scientific Notation I', 'Compare positive powers of 10.', 10),
(441, 23, NULL, NULL, 'Convert scientific notation to standard form.', 11),
(442, 23, NULL, NULL, 'Write large numbers in scientific notation.', 12),
(443, 23, 'Real Number System', 'Scientific Notation II', 'Compare negative powers of 10.', 13),
(444, 23, NULL, NULL, 'Convert scientific notation to standard form.', 14),
(445, 23, NULL, NULL, 'Convert standard form to scientific notation.', 15),
(446, 23, 'Data Graphs II', 'Scatter Plots', 'Create scatter plots.', 16),
(447, 23, NULL, NULL, 'Analyze scatter plots to determine relationships.', 17),
(448, 23, 'Probability', 'Fundamental Counting Principal', 'Calculate the number of possible events using the Fundamental Counting Principle.', 18),
(449, 23, NULL, NULL, 'Determine if events are independent of dependent.', 19),
(450, 24, 'Functions', 'Functions', 'Identify a function and its notation.', 0),
(451, 24, NULL, NULL, 'Determine the domain and range of a function.', 1),
(452, 24, NULL, NULL, 'Determine whether a relation is a function.', 2),
(453, 24, 'Functions', 'Special Functions', 'Use and solve linear and quadratic functions.', 3),
(454, 24, NULL, NULL, 'Use and solve absolute value and step functions.', 4),
(455, 24, 'Functions', 'Graphing Functions', 'Identify the graphs of linear, quadratic, and absolute value functions.', 5),
(456, 24, NULL, NULL, 'Identify the graph of a step function.', 6),
(457, 24, NULL, NULL, 'Use the vertical line test to determine if a graph is a function.', 7),
(458, 24, 'Ratios and Percents', 'Introduction to Ratios', 'Explore concepts related to ratios.', 8),
(459, 24, NULL, NULL, 'Identify different types of ratios.', 9),
(460, 24, NULL, NULL, 'Determine if two ratios are equivalent.', 10),
(461, 24, 'Ratios and Percents', 'Proportions and Unknowns', 'Explore the concepts of proportions.', 11),
(462, 24, NULL, NULL, 'Identify the different parts of a proportion.', 12),
(463, 24, NULL, NULL, 'Apply knowledge of proportions to solve for unknowns.', 13),
(464, 24, 'Linear Equations and Graphing', 'The Coordinate Plane', 'Define an identify parts of the coordinate plane.', 14),
(465, 24, NULL, NULL, 'Identify the quadrants of the coordinate plane.', 15),
(466, 24, NULL, NULL, 'Plot ordered pairs.', 16),
(467, 24, 'Linear Equations and Graphing', 'Slope', 'Calculate the slope of a line using the slope equation.', 17),
(468, 24, NULL, NULL, 'Classify slopes as positive, negative, zero, and undefined.', 18),
(469, 24, NULL, NULL, 'Determine the slope of a line given a graph of the line.', 19),
(470, 24, 'Linear Equations and Graphing', 'Slope-Intercept Form', 'Write an equation in slope-intercept form.', 20),
(471, 24, NULL, NULL, 'Graph an equation in slope-intercept form.', 21),
(472, 24, NULL, NULL, 'Find an equation from a graph.', 22),
(473, 25, 'Circles', 'Cylinders', 'Define a cylinder and its parts.', 0),
(474, 25, NULL, NULL, 'Find the surface area of a cylinder.', 1),
(475, 25, NULL, NULL, 'Find the volume of a cylinder.', 2),
(476, 25, 'Circles', 'Cones', 'Identify a cone and its parts.', 3),
(477, 25, NULL, NULL, 'Calculate the surface area of a cone.', 4),
(478, 25, NULL, NULL, 'Calculate the volume of a cone.', 5),
(479, 25, 'Polygons', 'Introduction to Polygons', 'Identify polygons.', 6),
(480, 25, NULL, NULL, 'Name polygons by their sides.', 7),
(481, 25, NULL, NULL, 'Classify polygons as regular or irregular.', 8),
(482, 25, 'Prisms and Pyramids', 'Nets', 'Identify the nets of prisms.', 9),
(483, 25, NULL, NULL, 'Identify the nets of pyramids.', 10),
(484, 25, NULL, NULL, 'Identify the nets of cylinders and cones.', 11),
(485, 25, 'Data Graphs I', 'Tree Diagrams, Tables, and Circle Graphs', 'Learn about the different ways to organize data.', 12),
(486, 25, NULL, NULL, 'Use tree diagrams, tables, and circle graphs to organize data and find solutions.', 13),
(487, 25, 'Data Graphs I', 'Bar Graphs and Histograms', 'Analyze data in bar graphs, double-bar graphs, and histograms.', 14),
(488, 25, NULL, NULL, 'Learn the steps to create a histogram.', 15),
(489, 25, 'Data Graphs II', 'Scatter Plots', 'Create scatter plots.', 16),
(490, 25, NULL, NULL, 'Analyze scatter plots to determine relationships.', 17),
(491, 25, 'Units', 'Dimensional Analysis', 'Evaluate the arrangement of variables in a problem.', 18),
(492, 25, NULL, NULL, 'Convert a single unit to a different unit within a system and between systems.', 19),
(493, 25, NULL, NULL, 'Convert derived units.', 20),
(494, 26, 'Inequalities', 'Inequalities', 'Set up inequalities from verbal sentences.', 0),
(495, 26, NULL, NULL, 'Graph inequalities on a number line.', 1),
(496, 26, 'Inequalities', 'Solving Inequalities', 'Solve simple inequalities using algebra properties.', 2),
(497, 26, 'Inequalities', 'Solving Compound Inequalities', 'Write a compound inequality.', 3),
(498, 26, NULL, NULL, 'Solve a compound inequality.', 4),
(499, 26, 'Inequalities', 'Linear Inequalities I', 'Write inequalities.', 5),
(500, 26, NULL, NULL, 'Convert inequalities into slope-intercept format.', 6),
(501, 26, NULL, NULL, 'Graph inequalities.', 7),
(502, 26, 'Inequalities', 'Linear Inequalities II', 'Write linear inequalities using negative numbers.', 8),
(503, 26, NULL, NULL, 'Change the sign of linear inequalities.', 9),
(504, 26, NULL, NULL, 'Graph inequalities using a sign change.', 10),
(505, 26, 'Absolute Value', 'Absolute Value', 'Relate the absolute value of a number with distance from a starting point.', 11),
(506, 26, NULL, NULL, 'Use math to simplify the absolute value of numbers.', 12),
(507, 26, 'Absolute Value', 'Solving Absolute Value Equations', 'Apply the rules of absolute value.', 13),
(508, 26, NULL, NULL, 'Solve absolute value equations.', 14),
(509, 26, 'Systems of Equations', 'Systems of Inequalities', 'Solve systems of linear inequalities by graphing.', 15),
(510, 27, 'Decimal Operations', 'Adding Decimals', 'Determine how to set up a decimal problem.', 0),
(511, 27, NULL, NULL, 'Add decimals to decimals.', 1),
(512, 27, NULL, NULL, 'Add decimals to whole numbers.', 2),
(513, 27, 'Units', 'Standard Units', 'Recognize the standard base units.', 3),
(514, 27, NULL, NULL, 'Identify the property each standard base unit measures.', 4),
(515, 27, NULL, NULL, 'Choose the correct unit to measure an object.', 5),
(516, 27, 'Units', 'Metric Units', 'Identify the common units of the metric system.', 6),
(517, 27, NULL, NULL, 'Use the basic prefixes of the metric system.', 7),
(518, 27, 'Units', 'Dimensional Analysis', 'Evaluate the arrangement of variables in a problem.', 8),
(519, 27, NULL, NULL, 'Convert a single unit to a different unit within a system and between systems.', 9),
(520, 27, NULL, NULL, 'Convert derived units.', 10),
(521, 27, 'Units', 'Converting Fahrenheit to Celsius', 'Convert from Celsius to Fahrenheit.', 11),
(522, 27, NULL, NULL, 'Covert from Fahrenheit to Celsius.', 12),
(523, 27, 'Introduction to Fractions', 'Simplifying Fractions', 'Find the greatest common factor (GCF).', 13),
(524, 27, NULL, NULL, 'Simplify fractions using division.', 14),
(525, 27, NULL, NULL, 'Compare fractions by simplifying.', 15),
(526, 27, 'Equations', 'One-Step Equation Word Problems', 'Solve one-step equations from word problems.', 16),
(527, 27, NULL, NULL, 'Solve one-step equations with decimals and fractions.', 17),
(528, 27, 'Equations', 'Multistep Equations', 'Solve multistep equations.', 18),
(529, 28, 'Real Number System', 'Prime Factorization', 'Learn about prime and composite numbers.', 0),
(530, 28, NULL, NULL, 'Find factors of natural numbers.', 1),
(531, 28, NULL, NULL, 'Find prime factorizations of natural numbers.', 2),
(532, 28, 'Radicals', 'Perfect Squares and Square Roots', 'Identify perfect squares.', 3),
(533, 28, NULL, NULL, 'Find the square root of perfect squares.', 4),
(534, 28, NULL, NULL, 'Approximate the square root of whole numbers.', 5),
(535, 28, 'Radicals', 'Cube Roots', 'Find cube roots of numbers.', 6),
(536, 28, NULL, NULL, 'Solve cubic equations.', 7),
(537, 28, 'Radicals', 'Simplifying Square Roots', 'Find the principal and negative square root.', 8),
(538, 28, NULL, NULL, 'Simplify square roots to find the exact answer.', 9),
(539, 28, 'Radicals', 'Radical Expressions', 'Simplify radical expressions.', 10),
(540, 28, 'Triangles', 'Inequality, Right Triangles, and the Pythagorean Theorem', 'Use the Triangle Inequality Theorem to determine whether you can draw a triangle.', 11),
(541, 28, NULL, NULL, 'Identify the parts of a right triangle.', 12),
(542, 28, NULL, NULL, 'Solve for the missing side of a right triangle using the Pythagorean Theorem.', 13),
(543, 28, 'Linear Equations and Graphing', 'Distance and Midpoint Formulas', 'Calculate the distance between two points using the Distance Formula.', 14),
(544, 28, NULL, NULL, 'Determine the midpoint between two points using the Midpoint Formula.', 15),
(545, 28, 'Special Equations', 'Radical Equations', 'Solve for x in rational equations.', 16);
SELECT setval('ipl_entries_id_seq', 545);
