"""Add correlation report models: State, Standard, Module, ModuleStandardMapping

Revision ID: 8202d014912d
Revises: 55ceb09cf793
Create Date: 2025-08-08 11:11:03.817641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8202d014912d'
down_revision = '55ceb09cf793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('acronym', sa.String(length=10), nullable=True),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_acronym'), ['acronym'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_title'), ['title'], unique=False)

    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=False),
    sa.Column('standard_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standards_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_standard_type'), ['standard_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_subject'), ['subject'], unique=False)

    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_code'), ['code'], unique=True)

    op.create_table('module_standard_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'standard_id', 'grade_level', name='unique_module_standard_grade')
    )
    with op.batch_alter_table('module_standard_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_module_grade_subject', ['module_id', 'grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_standard_mappings_grade_level'), ['grade_level'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_standard_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_standard_mappings_grade_level'))
        batch_op.drop_index('idx_module_grade_subject')

    op.drop_table('module_standard_mappings')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_code'))

    op.drop_table('states')
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standards_subject'))
        batch_op.drop_index(batch_op.f('ix_standards_standard_type'))
        batch_op.drop_index(batch_op.f('ix_standards_grade_level'))
        batch_op.drop_index(batch_op.f('ix_standards_code'))

    op.drop_table('standards')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_title'))
        batch_op.drop_index(batch_op.f('ix_modules_subject'))
        batch_op.drop_index(batch_op.f('ix_modules_acronym'))

    op.drop_table('modules')
    # ### end Alembic commands ###
