"""Restructure models for clean standards/modules/mappings

Revision ID: e753b30421b6
Revises: 8202d014912d
Create Date: 2025-08-08 17:14:31.749638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e753b30421b6'
down_revision = '8202d014912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_standard_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('idx_module_grade_subject'))
        batch_op.drop_index(batch_op.f('ix_module_standard_mappings_grade_level'))
        batch_op.drop_constraint(batch_op.f('unique_module_standard_grade'), type_='unique')
        batch_op.drop_column('id')
        batch_op.drop_column('grade_level')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_modules_acronym'))
        batch_op.drop_index(batch_op.f('ix_modules_subject'))
        batch_op.drop_index(batch_op.f('ix_modules_title'))
        batch_op.create_unique_constraint('uq_module_title_subject', ['title', 'subject'])
        batch_op.drop_column('acronym')
        batch_op.drop_column('description')

    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('framework', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('grade_band', sa.String(length=10), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('grade_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_standards_code'))
        batch_op.drop_index(batch_op.f('ix_standards_grade_level'))
        batch_op.drop_index(batch_op.f('ix_standards_standard_type'))
        batch_op.drop_index(batch_op.f('ix_standards_subject'))
        batch_op.create_index('ix_framework_subject_grade', ['framework', 'subject', 'grade_level'], unique=False)
        batch_op.create_unique_constraint('uq_framework_code', ['framework', 'code'])
        batch_op.drop_column('standard_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_type', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint('uq_framework_code', type_='unique')
        batch_op.drop_index('ix_framework_subject_grade')
        batch_op.create_index(batch_op.f('ix_standards_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_standard_type'), ['standard_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_standards_code'), ['code'], unique=False)
        batch_op.alter_column('grade_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('grade_band')
        batch_op.drop_column('framework')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('acronym', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint('uq_module_title_subject', type_='unique')
        batch_op.create_index(batch_op.f('ix_modules_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_modules_acronym'), ['acronym'], unique=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('active')
        batch_op.drop_column('grade_level')

    with op.batch_alter_table('module_standard_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unique_module_standard_grade'), ['module_id', 'standard_id', 'grade_level'])
        batch_op.create_index(batch_op.f('ix_module_standard_mappings_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('idx_module_grade_subject'), ['module_id', 'grade_level'], unique=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###
